### ISSUE TITLE
Incompatible with Rider 2022.2 EAP

### ISSUE THREAD

**Issue by mattjohnsonpint** [matkoch/resharper-verify#10]
I updated to the new Rider 2022.2 EAP and was given this warning:

![image](https://user-images.githubusercontent.com/1396388/169902497-c672421b-140b-4fe8-9da5-2f28bc058b57.png)

**Comment by matkoch** [comment]
Plugin is available now as 2022.2.0-eap01.

**Comment by SimonCropp** [comment]
@matkoch thanks ❤️
