### ISSUE TITLE
Not working in Visual studio 2022 professional Version 17.2.2

### ISSUE THREAD

**Issue by wallyrion** [matkoch/resharper-verify#11]
I upgraded visual studio to Version 17.2.2
Resharper also upgraded to 2022.1.20220428.100255
After that, the extension has become broken. Additional items ('Accept Received' And 'Compare Received / Verified') disappeared from the menu

**Comment by matkoch** [comment]
I just tried that and it's working for me. Can you try reinstalling the plugin and restarting Visual Studio? If the problem still persists, feel free to submit a repro solution.
