### ISSUE TITLE
Document how to disable the diff tool

### ISSUE THREAD

**Issue by ltrzesniewski** [matkoch/resharper-verify#14]
I expected this plugin to *replace* the diff tool being opened automatically. I dislike having diff windows being opened out of the blue. This also makes continuous testing impossible to use.

I've noticed you don't want to disable this by default (#1), but please document the fact that you can set the following environment variable in the unit testing options to achieve this behavior:

![image](https://user-images.githubusercontent.com/7913492/189748397-a706ce15-6338-49f7-96b7-746a5cdf3fe5.png)

Or implement a checkbox in the settings UI 🙂 

Thanks for the plugin BTW!

**Comment by SimonCropp** [comment]
@ltrzesniewski pull request?
