### ISSUE TITLE
Plugin does not seem to work in latest VS.

### ISSUE THREAD

**Issue by andre-artus** [matkoch/resharper-verify#25]
I have ReSharper and the latest version of the resharper-verify plugin installed, but the Accept and Compare options are no longer available in the context menu. It worked before but I have since updated Visual Studio, ReSharper, the Verify plugin, and the various nuget packages (xunit, verify, etc.). 

For completeness sake I will mention that I did restart VS after updating everything.

![image](https://github.com/matkoch/resharper-verify/assets/5009941/cb814a7a-e247-4271-a19e-26854dca0a39)

Microsoft Visual Studio Community 2022
Version 17.7.4
VisualStudio.17.Release/17.7.4+34031.279
Microsoft .NET Framework
Version 4.8.09037

Installed Version: Community

Visual C++ 2022   00476-80000-00000-AA234
Microsoft Visual C++ 2022

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.7.273.65229
ASP.NET and Web Tools

ASP.NET Web Frameworks and Tools 2012   17.7.273.65229
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   17.7.273.65229
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.7.273.65229
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.7.0-3.23416.8+43b0b05cc4f492fd5de00f6f6717409091df8daa
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   17.0.23189.3
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Entity Framework Core Power Tools   2.5
Adds useful design-time EF Core DbContext features to the Visual Studio Solution Explorer context menu.

Extensibility Message Bus   1.4.34 (main@d5ab18b)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

GitHub Copilot   1.110.0.0 (v1.110.0.0@9f24d0f53)
GitHub Copilot is an AI pair programmer that helps you write code faster and with less work.

GitHub Copilot Agent   1.110.389 (v1.110.0)

Linux Core Dump Debugging   1.0.9.34031
Enables debugging of Linux core dumps.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.7.27 (547ea6f)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.50628.1 Commit Hash:f9e713b25f69afd3ced63d934e0722003b73c121
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   6.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Progress Telerik UI for Blazor Extension   2023.2.911.73
Progress® Telerik® UI for Blazor Extension

Python - Django support   17.0.23189.3
Provides templates and integration for the Django web framework.

Python - Profiling support   17.0.23189.3
Profiling support for Python projects.

Python with Pylance   17.0.23189.3
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Razor (ASP.NET Core)   17.7.3.2333001+0ab18affdf2a37647768d0e25f5f021bee6257a1
Provides languages services for ASP.NET Core Razor.

Scroll Tabs   1.0.22
Allows you to scroll through open document tabs using the mouse wheel

SQL Server Data Tools   17.7.10.1
Microsoft SQL Server Data Tools

SQL Server Integration Services   16.0.5228.0
Microsoft SQL Server Integration Services Designer
Version 16.0.5228.0

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.20829.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.7.0-3.23416.8+43b0b05cc4f492fd5de00f6f6717409091df8daa
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Linux Development   1.0.9.34031
Visual C++ for Linux Development

Visual F# Tools   17.7.0-beta.23314.10+e612cf93b989503c89e3a5830090062b7ab5e143
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.7.0.216 (d17-7@133ddef)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.7.3.9 (remotes/origin/d17-7@796d191def)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   13.2.1.2 (d17-5/a8a26c7)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: d9a6e87
    Java.Interop: xamarin/java.interop/d17-5@149d70fe
    SQLite: xamarin/sqlite/3.40.1@68c69d8
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d

**Comment by andre-artus** [comment]
Seems like the latest versions of Verify depend on C# 9 features, specifically ModuleInitializerAttribute, while my project is still .NET Framework 4.8 and an earlier version of C#.

I reverted Verify and Verify.XUnit to 18.x and now the Accept context menu is back . The compare menu is not showing but I don't recall seeing it before.

**Comment by SimonCropp** [comment]
@andre-artus Verify does not rely on the c# feature ModuleInitializerAttribute. it relies on .net feature of ModuleInitializer which has been supported in .net since v1
