### ISSUE TITLE
[Feature] Open verified files for any given test

### ISSUE THREAD

**Issue by bitbonk** [matkoch/resharper-verify#26]
When a test fails I can do _Compare Received/Verified_. But sometimes you want to have a look at the verified files for a give test even if the test passes. 

One use case is to quickly find and understand which of the verified files belong to which test. I know I can (usually) tell by the file name but they are often long and cryptic which makes this quite cumbersome.

Another use case is this: Sometime you wonder why a test passes when you think it should fail. In such a case it is often quite helpful to look at the verified output of that test.

It would be nice to have an action _Show Verified_ in addition to _Compare Received/Verified_.

**Comment by matkoch** [comment]
will be in the next version
