### ISSUE TITLE
Rider - Received and Verified had been swapped

### ISSUE THREAD

**Issue by phatnh2301** [matkoch/resharper-verify#29]
![image](https://github.com/user-attachments/assets/9318f5ca-d8fb-4713-9c80-2719eecb187e)
Rider 2024.2.2 
Verify 2024.2.0
I think you can add the button Swap Sides like Diff & Merge viewer﻿ of Rider 
![image](https://github.com/user-attachments/assets/519fc761-ace2-4631-b68a-217e24e6e4df)

**Comment by SimonCropp** [comment]
@phatnh2301  not sure i understand what u r asking for, but it might be this https://github.com/VerifyTests/DiffEngine/blob/main/docs/diff-tool.md#leftright-diff-behavior  ?

**Comment by matkoch** [comment]
That was [intentional](https://github.com/matkoch/resharper-verify/blob/master/CHANGELOG.md) to comply with the coloring for additions/deletions. I checked with the IntelliJ team, and it's a bit too much work to get coloring right while keeping _Received_ on the left, and _Verified_ on the right.

**Comment by matkoch** [comment]
It might be worth discussing this here once more: https://github.com/matkoch/resharper-verify/issues/17
