### ISSUE TITLE
Extension does not work

### ISSUE THREAD

**Issue by Ergel** [matkoch/resharper-verify#3]
Hi Mathias,

i have installed this Extension for Resharper (Version 2021.2) on Visual Studio Professional 2019 (Version 16.8.5)
I don't see the Menuitems related to Verify.
My Test-Project has dotnetFramework version 4.8 and i am using Verify.NUnit with Version 11.26.0

I would be glad if you could fix this issue.

With greetings from Germany
Özgür Ergel
![Resharper Version](https://user-images.githubusercontent.com/7081154/135411138-4ef566ac-7e49-4f64-8742-492fbefa9df9.PNG)
![VS and Framework Version](https://user-images.githubusercontent.com/7081154/135411146-c4cab697-c7fc-4019-8b82-e0d3e26bd8eb.PNG)

**Comment by batzen** [comment]
@matkoch I am having a similar issue with the Rider plugin where i can see the menu items, but trying to accept the received results as verified seems to do nothing.
Do you think that might be related, or should i create a separate issue?

**Comment by matkoch** [comment]
should be fixed
