### ISSUE TITLE
Only main file is available to compare, sub files are not presented for comparison

### ISSUE THREAD

**Issue by CommCody** [matkoch/resharper-verify#30]
I have a test case where I validate the response of an http call for a javascript file,

but the plugin only offers to compare the main files and not the supplemental files:
![image](https://github.com/user-attachments/assets/ebe253db-4981-4a10-90c4-cd407c049319)

This test uses Verify.Http

**Comment by SimonCropp** [comment]
i think i know what the problem is here. i will push a possible fix shortly

**Comment by CommCody** [comment]
Thank you @SimonCropp 

It's not urgent, I simply use the manual workaround to verify these files for now, but I will be happy to test any fixes.

**Comment by SimonCropp** [comment]
@CommCody can u try Verify 26.4.0

**Comment by CommCody** [comment]
I've updated to 26.4.4 and ensured the latest plugin version was installed and everything is fine now!

Thank you very much!
