### ISSUE TITLE
Rider "Verify Support" plugin buttons does nothing

### ISSUE THREAD

**Issue by zlepper** [matkoch/resharper-verify#5]
This is an almost straight copy from here: https://github.com/VerifyTests/Verify/issues/452

#### Describe the bug
I'm using Verify to test a source generator. The test itself runs fine and has the expected output. However, trying to use the "Accept received" and "Compare Accepted/Receives" buttons does nothing. As in nothing happens when I click those buttons. I have ensured that tests are allowed to start sub-processes. When the test fails a diff tool does start, so Rider can clearly be found by Verify. 

Logs from Rider, where I only started the IDE, found a failing test and clicked those buttons. 
[rider verify logs.zip](https://github.com/VerifyTests/Verify/files/7768264/rider.verify.logs.zip)

And video in case my rambling didn't make any sense:

https://user-images.githubusercontent.com/1499810/147223348-8945bd14-0f98-42ea-989e-4f57801441d4.mp4

#### Minimal Repro

Here is a somewhat minimal solution that has a source generator and everything. The buttons still don't work. 
[VerifyBug.zip](https://github.com/VerifyTests/Verify/files/7768321/VerifyBug.zip)

Rider version:
```
JetBrains Rider 2021.3.1
Build #RD-213.5744.299, built on December 8, 2021
Licensed to Rasmus Hjelmberg Hansen
Subscription is active until September 19, 2022.
Runtime version: 11.0.13+7-b1751.19 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
.NET Framework 4.0.30319.42000
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 12
Registry:
    ide.mac.bigsur.window.with.tabs.enabled=false
    rdclient.asyncActions=false
    indexing.enable.entity.provider.based.indexing=false
    ide.new.project.model.index.case.sensitivity=true

Non-Bundled Plugins:
    verify-rider (2021.3.0)
    org.antlr.intellij.plugin (1.17)
    idea.plugin.protoeditor (213.5744.224)
    com.intellij.resharper.StructuredLogging (2021.3.0.177)
    com.intellij.resharper.HeapAllocationsViewer (2021.3.0)
    com.intellij.ideolog (203.0.27.0)
    com.intellij.plugin.adernov.powershell (2.0.9)

```

Verify Support plugin version: `2021.3.0`

**Comment by lars-erik** [comment]
We have the same issue on a freshly installed mac with Rider. (all newest versions)
Neither Verify.NUnit nor the Verify plugin pops any diff. (Nor does the approve command work)
For now we're working around it using command-D to diff the files.

**Comment by SimonCropp** [comment]
this will be fixed in the next release via https://github.com/matkoch/resharper-verify/commit/137bad320cfaa4e6de9c3ac146be175c31f44ccb

**Comment by milkshakeuk** [comment]
This still seems to be broken for me, latest rider and plugin windows 11.
![VerifyExample2](https://user-images.githubusercontent.com/1087376/155409056-4baaf0a1-219c-4e4e-ae1c-48840ec53d27.gif)

**Comment by matkoch** [comment]
@milkshakeuk can we communicate through one issue? I already mentioned what's needed to troubleshoot this: https://github.com/matkoch/resharper-verify/issues/8#issuecomment-1049229566

**Comment by milkshakeuk** [comment]
@matkoch yes using the original issue now, sorry.

**Comment by SimonCropp** [comment]
can u try 2022.1.0
