### ISSUE TITLE
How do you set the preferred diff engine?

### ISSUE THREAD

**Issue by milkshakeuk** [matkoch/resharper-verify#8]
When I run the tests in rider devenv.exe (visual studio 2022) keeps popping up (one of each nunit test case).

How do I prevent visual studio popping up? and then just accepting the received with the plugin, as currently it does nothing when I try to accept, either when visual studio is still open or when I close it.

![VerifyExample](https://user-images.githubusercontent.com/1087376/155108495-58c35de6-a869-4e98-89f6-00095d4da045.gif)

**Comment by milkshakeuk** [comment]
It would be great if anyone could help, this plugin seems useful if it were to work.

**Comment by matkoch** [comment]
See https://github.com/matkoch/resharper-verify/pull/1

I still think the pull request would be good, but it's @SimonCropp's call :)

**Comment by milkshakeuk** [comment]
@matkoch this did not solve my issue, this plugin still does not work, what do I need to do to make it work? what am I missing?
![VerifyExample2](https://user-images.githubusercontent.com/1087376/155409056-4baaf0a1-219c-4e4e-ae1c-48840ec53d27.gif)

**Comment by matkoch** [comment]
that looks unrelated to the original issue here. visual studio doesn't open anymore, right?

try starting Rider in [internal mode](https://rider-support.jetbrains.com/hc/en-us/articles/207327910-How-to-run-JetBrains-Rider-in-Internal-Mode) and check if you can spot any exceptions (red icon at the right bottom).

**Comment by milkshakeuk** [comment]
not seeing any exceptions.
![image](https://user-images.githubusercontent.com/1087376/155412608-36f3626b-0d8f-48a8-a6d6-615f91ecaf07.png)

**Comment by matkoch** [comment]
sorry but i can't help you then

**Comment by SimonCropp** [comment]
can you try version 2022.1.0

**Comment by milkshakeuk** [comment]
> can you try version 2022.1.0

It seems to work now with 2022.1.0 rider and 2022.1.0 plugin.
how to prevent IDEs popping up with the diff and just use the plugin?
